#!/bin/bash

# --- Configuration ---
FILE_PATH="/tmp/preparing_data38.txt"  # Change this to the path of your actual text file
TARGET_URL="https://docs.google.com/forms/d/e/1FAIpQLSc2iBPJXs8BxcD2uVVmNeNOMMyZRWQ141AieWt9QjL8CTlMcA/formResponse"
RESPONSE_FILE="/tmp/execute_response.txt"
DATA_BODY=@$FILE_PATH

# Optional: If this endpoint requires you to be logged in, 
# point this to the cookie file generated by your previous login script.
# COOKIE_FILE="/tmp/wms_cookies.txt" 

# --- 1. File Verification ---
if [ ! -f "$FILE_PATH" ]; then
    echo "Error: File '$FILE_PATH' does not exist."
    exit 1
fi

echo "Reading content from '$FILE_PATH' and submitting to WMS..."

# --- 2. Execute Request ---
# -s: Silent mode (hides the progress bar)
# -w "%{http_code}": Outputs the HTTP status code at the very end
# -o "$RESPONSE_FILE": Saves the server's reply to a temporary file
# -d "@$FILE_PATH": The '@' tells curl to read the content directly from the file

HTTP_STATUS=$(curl -s -X POST "$TARGET_URL" \
    -H 'Accept: application/json, text/plain, */*' \
  	-H 'Accept-Language: en-US,en;q=0.9,th;q=0.8' \
  	-H 'Connection: keep-alive' \
  	-H 'Content-Type: application/json' \
    -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0' \
    --data-raw "$DATA_BODY" \
	--insecure \
    -w "%{http_code}" \
    -o "$RESPONSE_FILE")
    
    # NOTE: If you need session authentication, add this line above the -d flag:
    # -b "$COOKIE_FILE" \

# --- 3. Evaluate the Result ---
if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
    echo "✅ Success! (HTTP Status: $HTTP_STATUS)"
    echo "--- Server Response ---"
    cat "$RESPONSE_FILE"
    echo ""
else
    echo "❌ Submission Failed. (HTTP Status: $HTTP_STATUS)"
    echo "--- Server Response ---"
    cat "$RESPONSE_FILE"
    echo ""
fi

# Clean up the temporary response file (optional)
rm -f "$RESPONSE_FILE"
